services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Syncs code changes in backend folder
      - ./models:/models  # Maps models directory for LLM
    environment:
      - PYTHONPATH=/app  # Ensures Python recognizes /app as root
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app  # Syncs code changes in frontend folder
    depends_on:
      - backend  # Ensures backend starts before frontend